name: Test

on:
  push:
    branches: [ main, develop, feature/*, bugfix/*, release/* ]
  pull_request:
    branches: [ main, develop ]

concurrency:
  group: "test-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Test Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Install dependencies
        run: uv sync --all-extras --all-packages
      
      - name: Run loader tests
        run: |
          cd packages/qdrant-loader
          uv run pytest tests/unit --cov=src --cov-report=term-missing -v
        continue-on-error: true
      
      - name: Run MCP server tests  
        run: |
          cd packages/qdrant-loader-mcp-server
          uv run pytest tests/unit --cov=src --cov-report=term-missing -v
        continue-on-error: true
      
      - name: Generate coverage report
        if: always()
        run: |
          echo "=== Test Summary ==="
          echo "Tests completed at $(date)"
          echo "Commit: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"